### ISSUE TITLE
Dependencias incumplidas, Elementary OS Freya

### ISSUE THREAD

**Issue by cholitoecuatoriano** [favadi/build-emacs#4]
Los siguientes paquetes tienen dependencias incumplidas:
 libghc-gconf-dev : Depende: libghc-base-dev-4.6.0.1-8aa5d
                    Depende: libghc-glib-dev-0.12.4-e3c24
                    Depende: libgconf2-dev pero no va a instalarse
 libgnutls-dev : Depende: libgnutls26 (= 2.12.23-12ubuntu2) pero 2.12.23-12ubuntu2.4 va a ser instalado
                 Depende: libgnutlsxx27 (= 2.12.23-12ubuntu2) pero no va a instalarse
                 Depende: libgnutls-openssl27 (= 2.12.23-12ubuntu2) pero 2.12.23-12ubuntu2.4 va a ser instalado
                 Depende: libgcrypt11-dev (>= 1.4.0) pero no va a instalarse
                 Depende: libtasn1-6-dev pero no va a instalarse
 libmagickcore-dev : Depende: libfreetype6-dev pero no va a instalarse
                     Depende: libgraphviz-dev pero no va a instalarse
                     Depende: libjasper-dev pero no va a instalarse
                     Depende: libtiff5-dev pero no va a instalarse
                     Depende: libwmf-dev pero no va a instalarse
                     Depende: libxext-dev pero no va a instalarse
 librsvg2-dev : Depende: libglib2.0-dev (>= 2.24.0) pero no va a instalarse
                Depende: libgdk-pixbuf2.0-dev (>= 2.23.5-2) pero no va a instalarse
                Depende: libcairo2-dev (>= 1.2.0) pero no va a instalarse
 libtiff4-dev : Depende: libtiff5-dev (> 4.0.3-6~) pero no va a instalarse
 libxft-dev : Depende: libfontconfig1-dev pero no va a instalarse
              Depende: libfreetype6-dev pero no va a instalarse
              Depende: libxrender-dev pero no va a instalarse
 xaw3dg-dev : Depende: libxmu-dev pero no va a instalarse

**Comment by favadi** [comment]
I don't have Elementary to test.
