### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by andrewsanchez** [favadi/build-emacs#5]
Hi Favadi,

Thanks for this awesome script.  It worked perfectly for me.  However, I'm having an issue getting .png's to display and some other things.  In trying to fix my issues, I need to uninstall and rebuild Emacs.  What's the best way to uninstall Emacs after using your script to build it?  I tried searching for Emacs in synaptic package manager and stow is the first result.  However, it doesn't look like Emacs is included in the installed files for this package  Thank you and sorry to post an issue here - I didn't know how else to get in contact with you.

**Comment by favadi** [comment]
Replace `$version` with the current version of emacs.

```
cd /usr/local/stow
stow -D emacs-"$version"
rm -rf /usr/local/stow/emacs-"version"
```
