### ISSUE TITLE
Now all new binaries install to /usr/local/stow/emacs-<version>/bin

### ISSUE THREAD

**Issue by SeaDude** [favadi/build-emacs#9]
From a fresh Ubuntu 16.04 install, I cloned the `build-emacs` repo and ran the install script as follows: 
```
clone https://github.com/favadi/build-emacs/blob/master/build-emacs.sh
cd to dir
chmod u+x build-emacs.sh
./build-emacs.sh
export PATH=$PATH:/usr/local/stow/emacs-<version>/bin
```
This installed emacs to `/usr/local/stow/emacs-<version>`. 

The problem I'm having is now, new binaries I install are placed at `/usr/local/stow/emacs-<version>/bin`. I'm not sure why this is happening. Any insights? 

Thanks

**Comment by SeaDude** [comment]
An example: 
Installing `gitbook-cli` (which is an `npm` module), using `sudo npm install gitbook-cli -g` puts the gitbook binary at `/usr/local/stow/emacs-25/bin/gitbook`. Now when I run any `gitbook` commands from the cli, I get the `"command not found"` error. I don't want the `PATH` for `gitbook` to be looking through `emacs-25/bin`.

**Comment by SeaDude** [comment]
I think this is the issue: https://paste.ubuntu.com/25892736/ 

For some reason, `/usr/local/bin` is symlinked to `/usr/local/stow/emacs-25.3/bin`. I scrutinized the script but don't see how/where this is happening. Any ideas?

**Comment by favadi** [comment]
@SeaDude I know why it happen, it is because `/usr/local/bin` does not exist when the `stow` command executed. I created https://github.com/favadi/build-emacs/pull/10 to address this. I haven't tested it myself, so it would be great help if you want to test it.

You should either remove everything in `/usr/local` (it should be safe to do that) or uninstall emacs with:

```
cd /usr/local/stow
stow -D emacs-"$version"
```

btw, `export PATH=$PATH:/usr/local/stow/emacs-<version>/bin` is unnecessary.

**Comment by favadi** [comment]
I will assume that it is fixed.

**Comment by SeaDude** [comment]
Testing now. I do have `man` and `var` symlinks in `/usr/local` as well. Not sure if I should add them to the script or not. I'll try without adding them first.

**Comment by SeaDude** [comment]
@favadi, this worked great. 
Steps: 
`rm -r * /usr/local/`
`./build_emacs.sh`
After emacs installed, I installed a couple binaries. All of them installed to the correct locations. The one dir that is missing from `/usr/local` is `man`. `var` appeared, but not `man`. Not sure what the implications of this. Thank you for your assistance.

**Comment by favadi** [comment]
We should do the same for man and var, can you create a PR?

**Comment by SeaDude** [comment]
`var` was created by the system somehow during install. I created a PR for adding the `man` dir.
